### ISSUE TITLE
Input and output not files

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-docker-specification#1]
According to https://github.com/openminted/omtd-component-executor/blob/6456f9661a51ca915c8d947fb08a062d066c4d4d/omtd-component-galaxy/src/main/java/eu/openminted/workflows/galaxywrappers/GalaxyToolExecutionCommand.java#L97 the input and output parameters are folders, not files.

The spec should be updated accordingly because it speaks about files:

> The component should use the info from this parameter when searching for input files and when generating output files - including the file names....

**Comment by mhabsaoui** [comment]
@reckart AFAIK according to galaxy/omtd doc, Galaxy will provide only in/out folders Paths.
The files will be provided from user and processed by the user App/Component which will profit from parameters info to it. So it seems it's OK with the specs... No ?

**Comment by reckart** [comment]
```
* It must be possible to set (with a parameter named --input) the input in the docker run in the following format: --input <PATH-TO-THE-INPUT-DATA>

* It must be possible to set (with a parameter named --output) the output in the docker run in the following format: --output <PATH-TO-THE-OUTPUT-DATA>

* There must not be any additional parameters to indicate data input/output locations

* Input and output data must be expected as files
```

From the feedback on the forum, it seems this part can be interpreted in multiple ways. I'm trying to fix it.

**Comment by mhabsaoui** [comment]
@reckart I agree, first time I have red it took some time to understand that "It must be possible to set" refers to the Galaxy workflow engine...

**Comment by galanisd** [comment]
The OMTD executors for 
* UIMA 
* GATE 
* Web services
were designed to use folders for input/output. 
E.g. see 
https://github.com/openminted/omtd-component-executor/blob/master/omtd-component-webservice/src/main/java/eu/openminted/component/webservice/WebServiceClient.java

It was the most generic thing we could think and compatible with Galaxy. 

We have to be specific in the spec what exactly we support.
SSH app requires I think a pattern /folder/* and not a path and this causes some issues.

**Comment by reckart** [comment]
@galanisd 

> SSH app requires I think a pattern /folder/* and not a path and this causes some issues.

That is probably the case right now because I pass the input/output parameters directly on to the PARAM_SOURCE_LOCATION and PARAM_TARGET_LOCATION parameters of the XmiReader/Writer. That is something I need to fix in the SSH code.

**Comment by mandiayba** [comment]
I think folder is good but I have a concern in how to handle a input directory with sub-directories: how to keep the structure of the input directory in the output directory to avoid mixing the output files.

**Comment by reckart** [comment]
I believe we do not have subfolders, do we?

Is there a specific folder structure provided to the (Docker) components by Galaxy? If yes, what does it look like... we would need to document it.

If there is no structure, then probably we should say in the spec that the input and output folders are expected to have no subfolders.

Btw. the DKPro Core components actually do handle subfolder preservation. Reader components add an information to the CAS which indicates the input root folder and the full path of each document being processed. The writer components use this information to calculate document path relative to the input root folder and combine that with the output root folder to determine the final target location of a file.

**Comment by mandiayba** [comment]
May be I wrong but I assume that we don't know what will be the structure of the corpus loaded by user in the registry. But, if we could document and ensure that there is no structure in the folders, it is probably better. If we keep the structure, (I think) that means all components of a workflow will have to preserve it.

**Comment by reckart** [comment]
@galanisd @mandiayba There must be some rules as to how the folders are structured. @antleb has defined some folder structure for stored corpora - I assume that structure must map in some way to the input and output folders. The question is: where is this structure documented and how does it map?

**Comment by reckart** [comment]
Let's continue the discussion on folder structure separately: https://github.com/openminted/omtd-docker-specification/issues/2

I am closing this issue now.
